# Generated by Django 4.1.2 on 2022-11-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.car'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
