name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "vegardwk"
          password: "dckr_pat_7hVaINCWNy5vwwR1DJynB5fqu18"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./OBLIG5/mysite/
          file: ./OBLIG5/mysite/Dockerfile
          push: true
          tags: "vegardwk/mysite-vega"
          #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
